version: 2

jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install
          command: pnpm install
  deploy:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  continuous-integration:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
